version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    ports:
      - 8881:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin